apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # On WSL, you can reach for local data from this path: /run/desktop/mnt/host/c/someDir
    # See: https://stackoverflow.com/questions/62812948/volume-mounts-not-working-kubernetes-and-wsl-2-and-docker
    path: /run/desktop/mnt/host/c/someDir/dockymfik-k8s/docker-app/data
